// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACip4sjtVy9cW-OiuIqwBLSHyiXRrcbCc',
    appId: '1:522219468655:web:c6a23e29ea9e174ec01a9a',
    messagingSenderId: '522219468655',
    projectId: 'smartbin-1818',
    authDomain: 'smartbin-1818.firebaseapp.com',
    databaseURL: 'https://smartbin-1818-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbin-1818.firebasestorage.app',
    measurementId: 'G-PGT9H20X4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR5lXOD6Of1kRf0FzrLVErW6dYVBaVpDI',
    appId: '1:522219468655:android:e3dae028329e1051c01a9a',
    messagingSenderId: '522219468655',
    projectId: 'smartbin-1818',
    databaseURL: 'https://smartbin-1818-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbin-1818.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxt7IFC4Qmp5FqF1338MVKF4zOV1pL7hY',
    appId: '1:522219468655:ios:5bf4d9d12ab0e834c01a9a',
    messagingSenderId: '522219468655',
    projectId: 'smartbin-1818',
    databaseURL: 'https://smartbin-1818-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbin-1818.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxt7IFC4Qmp5FqF1338MVKF4zOV1pL7hY',
    appId: '1:522219468655:ios:5bf4d9d12ab0e834c01a9a',
    messagingSenderId: '522219468655',
    projectId: 'smartbin-1818',
    databaseURL: 'https://smartbin-1818-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbin-1818.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACip4sjtVy9cW-OiuIqwBLSHyiXRrcbCc',
    appId: '1:522219468655:web:82c6081d83227d4ec01a9a',
    messagingSenderId: '522219468655',
    projectId: 'smartbin-1818',
    authDomain: 'smartbin-1818.firebaseapp.com',
    databaseURL: 'https://smartbin-1818-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbin-1818.firebasestorage.app',
    measurementId: 'G-2PQ4RM55DJ',
  );
}
